# Generated by Django 5.2.7 on 2025-10-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapi_app', '0002_alter_car_make_alter_car_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='insurancepolicy',
            name='policy_end_after_start',
        ),
        migrations.AddIndex(
            model_name='policyexpirylog',
            index=models.Index(fields=['logged_expiry_at'], name='carsapi_app_logged__616a83_idx'),
        ),
        migrations.AddConstraint(
            model_name='insurancepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='policy_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='policyexpirylog',
            constraint=models.UniqueConstraint(fields=('policy',), name='uniq_policy_once'),
        ),
    ]
